name: Installs HMAC secret
inputs:
  heroku-app:
    required: true
  source-branch:
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1
    - name: Get Heroku API Key
      run: |
        API_KEY=$(op read "op://Shape Docs GitHub Actions/Heroku API Key/password")
        echo "HEROKU_API_KEY=$(echo $API_KEY)" >> $GITHUB_ENV
      shell: bash
    - name: Add Heroku Git Remote
      run: heroku git:remote -a ${{ inputs.heroku-app }}
      shell: bash
    - name: Push to Heroku
      run: git push heroku ${{ inputs.source-branch }}:main
      shell: bash
