name: Build
on:
  workflow_dispatch: {}
  pull_request: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  NEXT_TELEMETRY_DISABLED: 1
  SHAPE_DOCS_BASE_URL: http://localhost:3000
  SHAPE_DOCS_PROJECT_CONFIGURATION_FILENAME: .shape-docs.yml
  NEXT_PUBLIC_SHAPE_DOCS_TITLE: Shape Docs
  NEXT_PUBLIC_SHAPE_DOCS_DESCRIPTION: Documentation for Shape's APIs
  NEXTAUTH_URL_INTERNAL: http://localhost:3000
  NEXTAUTH_SECRET: 336f7a926310cff425cea29556dce2a98859b8d234aa27968696c2e6f1cb7d34
  REDIS_URL: localhost
  POSTGRESQL_HOST: localhost
  POSTGRESQL_USER: dbuser
  POSTGRESQL_DB: db
  REPOSITORY_NAME_SUFFIX: -openapi
  GITHUB_WEBHOOK_SECRET: this-is-our-webhook-secret
  GITHUB_WEBHOK_REPOSITORY_ALLOWLIST:
  GITHUB_WEBHOK_REPOSITORY_DISALLOWLIST:
  GITHUB_CLIENT_ID: this-is-our-github-client-id
  GITHUB_CLIENT_SECRET: this-is-our-github-client-secret
  GITHUB_APP_ID: 123456
  GITHUB_PRIVATE_KEY_BASE_64: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCS2NaL3UyL3dubDA4R1BjeXdiSVc2QVdKdnhVL2o0V0g2UnkxODVPSHZDd0FBQUpBYW01MzdHcHVkCit3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQktjWi91Mi93bmwwOEdQY3l3YklXNkFXSnZ4VS9qNFdINlJ5MTg1T0h2Q3cKQUFBRUJ6T2htRGpuY3R0QSt3ai9USHRnWnN6MklRWjdLM2ovb0Z1OEZBNTMxTDhrcHhuKzdiL0NlWFR3WTl6TEJzaGJvQgpZbS9GVCtQaFlmcEhMWHprNGU4TEFBQUFDMlp2YjBCb1lYQmxMbVJyQVFJPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
